(cl:defpackage first_actionlib_sample-msg
  (:use )
  (:export
   "<DODISHESFEEDBACK>"
   "DODISHESFEEDBACK"
   "<DODISHESACTIONRESULT>"
   "DODISHESACTIONRESULT"
   "<DODISHESACTIONFEEDBACK>"
   "DODISHESACTIONFEEDBACK"
   "<DODISHESACTIONGOAL>"
   "DODISHESACTIONGOAL"
   "<DODISHESACTION>"
   "DODISHESACTION"
   "<DODISHESRESULT>"
   "DODISHESRESULT"
   "<DODISHESGOAL>"
   "DODISHESGOAL"
  ))

