// Generated by gencpp from file first_actionlib_sample/DoDishesResult.msg
// DO NOT EDIT!


#ifndef FIRST_ACTIONLIB_SAMPLE_MESSAGE_DODISHESRESULT_H
#define FIRST_ACTIONLIB_SAMPLE_MESSAGE_DODISHESRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_actionlib_sample
{
template <class ContainerAllocator>
struct DoDishesResult_
{
  typedef DoDishesResult_<ContainerAllocator> Type;

  DoDishesResult_()
    : toal_dishes_cleaned(0)  {
    }
  DoDishesResult_(const ContainerAllocator& _alloc)
    : toal_dishes_cleaned(0)  {
  (void)_alloc;
    }



   typedef uint32_t _toal_dishes_cleaned_type;
  _toal_dishes_cleaned_type toal_dishes_cleaned;




  typedef boost::shared_ptr< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> const> ConstPtr;

}; // struct DoDishesResult_

typedef ::first_actionlib_sample::DoDishesResult_<std::allocator<void> > DoDishesResult;

typedef boost::shared_ptr< ::first_actionlib_sample::DoDishesResult > DoDishesResultPtr;
typedef boost::shared_ptr< ::first_actionlib_sample::DoDishesResult const> DoDishesResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace first_actionlib_sample

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'first_actionlib_sample': ['/home/leon/catkin_ws/devel/share/first_actionlib_sample/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1388306baff26bc8e5ed88c5b72fd358";
  }

  static const char* value(const ::first_actionlib_sample::DoDishesResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1388306baff26bc8ULL;
  static const uint64_t static_value2 = 0xe5ed88c5b72fd358ULL;
};

template<class ContainerAllocator>
struct DataType< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_actionlib_sample/DoDishesResult";
  }

  static const char* value(const ::first_actionlib_sample::DoDishesResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Define the result\n\
uint32 toal_dishes_cleaned\n\
";
  }

  static const char* value(const ::first_actionlib_sample::DoDishesResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.toal_dishes_cleaned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoDishesResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_actionlib_sample::DoDishesResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_actionlib_sample::DoDishesResult_<ContainerAllocator>& v)
  {
    s << indent << "toal_dishes_cleaned: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.toal_dishes_cleaned);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_ACTIONLIB_SAMPLE_MESSAGE_DODISHESRESULT_H
